depot_points =
    {
	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
	"features": [
	    { "type": "Feature",
	      "properties": { "popup": "Motala Start 0 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 15.038395, 58.534174, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Hästholmen Depå 38 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.648209, 58.279582, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Gränna Depå 83 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.402347, 57.93431, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Huskvarna Depå 2010 103 km", "description": "Ersatte depån i Jönköping 2010", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.259675, 57.79162, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Jönköping Depå 105 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.232337, 57.786347, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Fagerhult Depå 134 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.117517, 57.994999, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Splash & Go 139 km", "description": "Bara vatten!<br><br>Only water!<br><br>Nur Wasser!", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.173307, 58.032758, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Hjo Depå 172 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.290509, 58.30268, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Karlsborg Depå 204 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.518518, 58.530903, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Boviken Depå 225 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.654689, 58.683139, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Hammarsundet Depå 255 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.938016, 58.809941, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Medevi Depå 272 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 14.958143, 58.674037, 0.0 ] } },
	    { "type": "Feature",
	      "properties": { "popup": "Motala Mål 295 km", "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null },
	      "geometry": { "type": "Point", "coordinates": [ 15.030155, 58.534712, 0.0 ] } }
	]
    }
